### ISSUE TITLE
Variable substitutions partly not working

### ISSUE THREAD

**Issue by ida** [collective/collective.contentrules.mailtogroup#4]
The variables ${namedirectory} and ${text} won't be substituted anymore since of version 1.5
Any idea what happened and how to fix?

**Comment by ida** [comment]
@cekk This is a friendly ping, in case you haven't noticed this ticket, yet. Your commit broke several var-substitutes, I guess, that wasn't intended, but do you think to fix it?
@kcleong Also a friendly ping, as you are the product's owner.

**Comment by cekk** [comment]
@ida thanks for the ping, i didn't received any notice about this issue.

Btw the solution is easy. Now the rule uses [plone.stringinterp](https://github.com/plone/plone.stringinterp) that doesn't have a substitution for ${text} and ${namedirectory}.

For *${text}* we created a separate plugin to do it: [collective.stringinterp.text] (https://pypi.python.org/pypi/collective.stringinterp.text) that should be added as dependency.

For *${namedirectory}* i think that we should copy the things done in collective.stringinterp.text (see the code on github for an example: https://github.com/RedTurtle/collective.stringinterp.text) directly in this product.

At this moment i'm a bit busy, but i could find some time in the next days..otherwise, if you want to try to fix it, you're welcome ;)

**Comment by ida** [comment]
Hi @cekk, thank for the infos! Yes, I also tested collective.stringinterp.text for the text-substitution ~ 2 months ago, and it wasn't much of a fuzz to implement it, as you suggest, just also don't have time right now and simply stick with vs. 1.3.1, in the meanwhile, so no pressure of my side. But good to know it's on the plate, so we (meh and meh clients) don't have to go with a fork. I might come back to it, too, let's see who's first ;)

**Comment by ida** [comment]
@cekk: Just in case you find the time to redo the regressions, please remind that the text-field's substitution needs to regard whether a receiving email's client is configured to show mails in HTML or in plain text (see the ripped out code of vs. 1.3 on how I had done that, following a doc of P. Bengtson, see: https://github.com/collective/collective.contentrules.mailtogroup/blob/1.3/collective/contentrules/mailtogroup/actions/mail.py#L157), TIA.

**Comment by ida** [comment]
@cekk Are you gonna restore the damage done, one day, or?

**Comment by ida** [comment]
@cekk So apparently I'm a witch-hunter, you've accidentally overseen a couple dozens lines of code and the other guys pushing the package further didn't notice either. Additionally I'm constantly accused to want you to work for free. I am closing this now. Thanks for your time.
